### ISSUE TITLE
SeAT 3.x Progress Tracking

### ISSUE THREAD

**Issue by leonjza** [eveseat/seat#262]
This ticket aims to track SeAT 3.x's outstanding TODO items and other progress that forms part of the migration to ESI. It will be continuously updated as progress is made.

# ~Alpha / Beta release blockers~
## Beta is tagged. Bug fixing now till final release
- [x] Add checks for cached loads from [Eseye responses](https://github.com/eveseat/eseye/blob/c2a2d87180f9feb6ac2d893a23673029bad3b217/src/Containers/EsiResponse.php#L240) to speed up updaters.
- [x] Make StyleCI happy in all eveseat/seat repositories.
- [x] Double check the "throttler" in `Seat\Eveapi\Jobs\Contracts\Corporation\Items` as there are unused variable warnings.
- [x] Issue ticket numbers that need to be closed first: 
  - [x] #253 (Standing Builder)
  - [x] #256 (User account status)
  - [x] #258 (Director corp access)
  - [x] #259 (Empty corp assets)
  - [x] #260 (User management)
- [x] Update the cache clearing command to clear the Eseye cache.
- [x] Update all packages to make use of Laravel [package discovery](https://laravel.com/docs/5.5/packages#package-discovery). 
- [x] ~Update eveseat/seat `composer.json` to prefer stable packages. Ensure the correct label for an alpha is used in the version tag.~
- [x] Document `php artisan seat:admin:login` command.

# Final release blockers
- [x] The eveapi package needs a major revamp to match up with all of the new models.
- [x] Create production, docker hub downloadable pipeline for SeAT distribution.
- [x] Ensure that no workers complain about deprecation, paged responses or have any other similar errors.
- [x] Update installation documentation for SeAT 3. Specifically remove supervisor specific documentation as Horizon handles all of that.
- [x] Update analytics code for error tracking. Specifically in the case of deprecated & paged endpoint warnings.
- [x] Fix up the character drowndown selector. The UI needs love.
- [x] Fix "main character" selection and tracking. Can be done as a flag on the User <-> Group pivot.
- [x] SeAT 3x Documentation. Figure out how to version the current docs and update!
- [x] Ensure a method exists that allows for integrations to determine a groups main `character_id`. This will be needed anyways for the profile view set the main character.
- [x] Hamburger side-menu collapse button does not work.
- [x] Fix unit testing errors in eveseat/eveapi
- [ ] ~Make the first SSO character that logs in a Superuser automatically.~
- [x] Test and fix tooltips application-wide.
- [x] Move settings to be applicable to a group and not single users anymore.
- [x] Fix up the notifications package to match the new models (All but starbases done. Will tackle in point release).
- [x] Rate limit the universe/structures endpoints as well as the contracts/items endpoints to prevent sudden IP banning.
- [x] Handle downtime and other ESI outages.
- [x] Add a data removal / purge page.
- [x] Add plugin update script to docker-seat-app.
- [x] Configure log rotation in `docker-compose.yml`.
- [x] Ensure that when the last user of a group is deleted, the group is cleaned up too.

### nice to haves
- [x] Add fittings view to character sheet
- [ ] Include container logs view in assets with containers
- [ ] Add corporation shareholders view
- [x] Document [observer](https://laravel.com/docs/5.5/eloquent#observers) logic for package developers to know when characters / corporations are deleted.

# other
- [x] Update example package to use package autodiscovery.

**Comment by herpaderpaldent** [comment]
@leonjza regarding `SeAT 3x Documentation. Figure out how to version the current docs and update!`:
http://docs.readthedocs.io/en/latest/versions.html
* You would need to tag version of the project.

**Comment by warlof** [comment]
discourse is using mail setup during the installation process to create SU user(s) and send an activation link by mail. Dunno if it can help. I find the current way with admin generator link quite more secure :/

**Comment by leonjza** [comment]
I have tagged v3.0.0-beta today. Installation is very similar to 2.x. I have updated the original installer to install fine on Ubuntu 16.x.

Run the prep on a fresh box with `bash <(curl -fsSL https://git.io/v15KU)` and then the installer with `seat install:production --minimum-stability beta`.

**Comment by leonjza** [comment]
Excellent thank you @MrBMT !

**Comment by MrBMT** [comment]
@ppfeufer Unless changes are made do SeAT, it won't run on PHP 7.2. The reason behind this being mcrypt is required by some of the vendor libraries used and support for mcrypt was completely removed from PHP 7.2, so in your situation you would still need PHP 7.1 to be installed anyway.

**Comment by leonjza** [comment]
> For the install script. Please check if maybe a newer version of PHP is already installed, like PHP7.2 for example. In that case, please do NOT force the system to install PHP7.1 as it might f**k up things badly.

Like @MrBMT said, the installer is meant for fresh boxes only. If you are not installing on a fresh host, either install manually or use a Docker setup (which will have pre-built containers soon™).

I hope to try and get SeAT's PHP 7.2 compatibility sorted before the 3.0.0 final tag, but that depends.

**Comment by ppfeufer** [comment]
If you're talking about Laravel, that's no longer dependent on mcrypt, since 5.1 if I'm not mistaken. And on a quick scan of the SeAT packages we couldn't find any dependecies on mcrypt. Might be worth looking into.

**Comment by MrBMT** [comment]
Having had another look, the `paragonie` and `sebastian` vendor packages installed with my SeAT installation were the two that mentioned mcrypt; paragonie however only mentions it for adding the random_bytes function to PHP installs lower than 7.0 (so is not applicable here) and it doesn't look to utilised by sebastian either.

However, as SeAT has depended on mcrypt previously it won't have been tested on PHP 7.2; so even if mycrypt was removed from the SeAT middleware requirements, there's still no guarantee things would work properly.

**Comment by warlof** [comment]
@ppfeufer following manual installation book is exploiting php-fpm as php processor which allow you to use multiple version of it on the same server. Even if they are based on nginx, you can make it works with apache using apache-fastcgi.

**Comment by leonjza** [comment]
Thanks to @MrBMT the SeAT tool now works on Debian 8 + 9 too. So to get the beta:

```bash
bash <(curl -fsSL https://git.io/seat-installer)
seat install:production --minimum-stability beta
```

**Comment by leonjza** [comment]
@kwazulueve please join us on Slack for further support. Looks like you got SeAT 2x (which happens if your php version is older than 7.1). Also make sure you installed on a fresh OS install.

**Comment by leonjza** [comment]
Just tagged a bunch of new package versions. Unfortunately for the upgrade this time round you need to re-install your Beta instance (hey, this is a beta after all). With the docker install you need to `docker-compose down` and remove the database volume (`docker volume rm docker-compose_mariadb-data`) before pulling and starting it up again.

If everything goes well, this might be the last beta versions before a final. Holding thumbs!

**Comment by Nekses** [comment]
Upgrade path from 2.0 is possible? Just wanted to ask in advance before going further.

**Comment by herpaderpaldent** [comment]
See here: https://eveseat.github.io/docs/guides/upgrade/seat2_to_3/

**Comment by warriorsoul15** [comment]
How do we do a new install of 3.0 on ubuntu these days?

**Comment by MrBMT** [comment]
@warriorsoul15 If you're using Ubuntu 16.04 on a fresh box:

```
bash <(curl -fsSL https://git.io/seat-installer)
seat install:production --minimum-stability beta
```

If you're using Ubuntu 18.04 or already have things running on a box - manually:
https://eveseat.github.io/docs/guides/installation/ubuntu/

**Comment by herpaderpaldent** [comment]
no alternative: Docker is first choice by developer! 
ofc you can always go with the other one if you wish

**Comment by MrBMT** [comment]
Docker doesn't work in some environments, and has disadvantages such as making it considerably harder to integrate third party SeAT plugins. You should always just use whatever method works best for you.

**Comment by herpaderpaldent** [comment]
> has disadvantages such as making it considerably harder to integrate third party SeAT plugins

which is only halfway true. We have noticed that that currently with BETA the packages are not rebuild, but qu1ckkk already addressed this. So for production this argument does not count. 

> You should always just use whatever method works best for you.

that is true and for 80% of the users docker works just fine.

**Comment by flyingferret** [comment]
Folling the migration workflow I get the following 

`
Using version ^2.0 for warlof/seat-migrator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for eveseat/services (locked at 2.0.12, required as 2.0.*) -> satisfiable by eveseat/services[2.0.12].
    - warlof/seat-migrator 2.0.0 requires eveseat/services 2.0.13 -> satisfiable by eveseat/services[2.0.13].
    - warlof/seat-migrator 2.0.0-alpha1 requires eveseat/services 2.0.13 -> satisfiable by eveseat/services[2.0.13].
    - warlof/seat-migrator 2.0.0-alpha2 requires eveseat/services 2.0.13 -> satisfiable by eveseat/services[2.0.13].
    - warlof/seat-migrator 2.0.1 requires eveseat/services 2.0.13 -> satisfiable by eveseat/services[2.0.13].
    - Conclusion: don't install eveseat/services 2.0.13
    - Installation request for warlof/seat-migrator ^2.0 -> satisfiable by warlof/seat-migrator[2.0.0, 2.0.0-alpha1, 2.0.0-alpha2, 2.0.1].
Installation failed, reverting ./composer.json to its original content.
`

I'm not a great coder or anything just been stuck with running the admin for the alliance so, any help welcome.

**Comment by leonjza** [comment]
@flyingferret best to hop into slack and ask @warlof in the support channel about the migration tool.

**Comment by warlof** [comment]
Hum... Most important, what the hell append into this ticket?

Please, open a new one dedicated to your problem 😥

Btw, ensure your seat2 is up to date before installing Migrator on it.

**Comment by leonjza** [comment]
Its here! 🎉
