### ISSUE TITLE
3.1 Tracking

### ISSUE THREAD

**Issue by leonjza** [eveseat/seat#394]
## This ticket aims to track the changes planned for v3.1

In summary, the biggest milestone for v3.1 is an entire ACL system revamp. Discussions are **encouraged**.

### ACL Revamp
- [x] Experiment with [Gates](https://laravel.com/docs/5.5/authorization) to write policies for access control. Protecting routes should be the primary concern.
- [x] Collapse the various [bouncers](https://github.com/eveseat/web/tree/master/src/Http/Middleware/Bouncer).
- [ ] Consider an ACL policy for recruiters. This type of role is probably the most requested and sucks in its current implementation.
- [x] Consider ACL policies that keep Alliance level access in mind, and not just the original corporation level stuff.
- [x] Get automated group subscriptions working based on corporation membership, in game roles or other criteria.
- [x] Revamp the UI for working with roles. 
- [ ] When working with the access checker logic, ensure that the components are re-usable to cater for when SeAT starts to move into the external services space.

### Name resolution
Since ESI, name resolution has become quite a headache based on how SeAT used to manage this in the 2.x days. Currently there is a crappy UI driven name resolution service that makes life hard.

- [x] Add a job that continuously discovers unresolved id's and populates a `universe_names` table (or similar)
- [ ] Experiment with writing a trait to add columns if fields like `character_id`, `corporation_id` or anything we can resolve exists.

**Comment by herpaderpaldent** [comment]
As for: `Get automated group subscriptions working based on corporation membership, in game roles or other criteria.`
One of the aspects of my https://github.com/herpaderpaldent/seat-groups does exactly this: `auto`-group called. 
I have other aspects in this Package: 
* Open-group: Users that qualify can opt-in and opt-out into groups and get assigned the corresponding role->permission
* Managed-group: Users that qualify can apply for the role, a Manager might accept or deny that request
* Hidden-group: Users might be assigned to a group by the admin
All of this groups are protected by default from members continue carrying the role, when they don't qualify for the role anymore (f.e. if they leave the corp or they have been purged) 

Do you want to integrate this?
