### ISSUE TITLE
4.1.x TODO

### ISSUE THREAD

**Issue by warlof** [eveseat/seat#617]
This is a small ticket to list all stuff which could be handled in 4.1.x version.
4.0.x is now freeze and will only receive bug fix - *trying* to turn it gold for somewhat in June.

# ORM

## Characters

- [ ] remove [CharacterSkill](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Character/CharacterSkill.php) and leverage relation [CharacterInfo.skills](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Character/CharacterInfo.php#L566-L574) to a pivot between CharacterInfo and InvType
- [ ] remove [CharacterSkillQueue](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Skills/CharacterSkillQueue.php) and leverage relation [CharacterInfo.skill_queue](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Character/CharacterInfo.php#L576-L582) to a pivot between CharacterInfo and InvType
- [ ] remove [CharacterContract](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Contracts/CharacterContract.php) and leverage relation [CharacterInfo.contracts](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Character/CharacterInfo.php#L379-L387) to a pivot between CharacterInfo and ContractDetail
- [ ] remove [CharacterImplant](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Clones/CharacterImplant.php) and leverage relation [CharacterInfo.implants](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Character/CharacterInfo.php#L429-L437) to a pivot between CharacterInfo and InvType

## Corporations

- [ ] remove [CorporationContract](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Contracts/CorporationContract.php) and leverage relation [CorporationInfo.contracts](https://github.com/eveseat/eveapi/blob/9688a481e1573170ab2dc898dd0fc58020cca278/src/Models/Corporation/CorporationInfo.php#L312-L320) to a pivot between CorporationInfo and ContractDetail

# Authentication

## API

- [ ] Add OAuth2 and Passport implementation
